add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$python\
$character
"""

palette = "grayscale"

[palettes.grayscale]
bg        = "#1e1e1e"
fg        = "#c0c0c0"
muted     = "#9a9a9a"
dark      = "#6f6f6f"
lighter   = "#e0e0e0"
red       = "#ff0000"

[directory]
style = "fg:fg"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = " "
style = "fg:muted"

[git_status]
style = "fg:dark"

[character]
success_symbol = "[❯](fg:lighter)"
error_symbol   = "[❯](fg:dark)"

[python]
symbol = ""
style = "fg:lighter"
format = '[ $symbol( $version) [\(($virtualenv)\)](fg:red) ]($style)'
